When creating a srvtab based on a just-downloaded keytab, extract the srvtab key before merging the keytab into an existing file. Otherwise, if the new keys had a lower kvno than the old keys (possible after deleting and recreating the object), the wrong key would be extracted for the srvtab.

diff --git a/tests/data/cmd-fake b/tests/data/cmd-fake
--- a/tests/data/cmd-fake
+++ b/tests/data/cmd-fake
@@ -50,11 +50,16 @@ setattr)
     fi
     case "$1" in
     service/fake-srvtab)
-        if [ "$3" != "kaserver" ] ; then
-            echo "Invalid attribute value $3" >&2
-            exit 1
+        if [ "$3" = "kaserver" ] ; then
+            touch sync-kaserver
+        else
+            if [ "$3" = "" ] ; then
+                rm sync-kaserver
+            else
+                echo "Invalid attribute value $3" >&2
+                exit 1
+            fi
         fi
-        touch sync-kaserver
         ;;
     *)
         echo "Looking at sync attribute of wrong keytab" >&2
